# Google Cloud App Engine configuration for Aerodrome AI Agent
# Optimized for production deployment with scaling and performance features

runtime: python311
service: aerodrome-ai-agent

# Instance configuration
instance_class: F4_1G
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.8
  min_pending_latency: 100ms
  max_pending_latency: 500ms

# Network configuration
network:
  forwarded_ports:
    - 8080

# Environment variables
env_variables:
  # API Configuration
  API_TITLE: "Aerodrome AI Agent API"
  API_VERSION: "1.0.0"
  API_DESCRIPTION: "AI-powered Aerodrome Protocol assistant"
  PORT: "8080"
  ENV: "production"
  
  # Security - Set these in Google Cloud Console Secret Manager instead
  # API_KEY: "your-production-api-key"  # Use Secret Manager
  
  # Rate Limiting
  RATE_LIMIT_REQUESTS: "100/minute"
  RATE_LIMIT_QUERY: "10/minute"
  
  # Brain Configuration  
  CONFIDENCE_THRESHOLD: "0.3"
  MAX_CONCURRENT_QUERIES: "10"
  HEALTH_CHECK_INTERVAL: "30"
  
  # CORS Configuration
  ALLOWED_ORIGINS: "*"
  TRUSTED_HOSTS: "*"
  
  # Gemini Configuration
  GEMINI_MODEL: "gemini-2.0-flash-001"
  
  # Logging
  LOG_LEVEL: "INFO"
  ENABLE_STRUCTURED_LOGGING: "true"

# Resource limits
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health checks
liveness_check:
  path: "/health/live"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 1

readiness_check:
  path: "/health/ready"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1
  app_start_timeout_sec: 300

# Error handlers
error_handlers:
  - file: static/404.html
    error_code: 404
  - file: static/500.html
    error_code: 500

# Static file handlers (for documentation)
handlers:
  - url: /static
    static_dir: static
    secure: always
    
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon\.ico
    secure: always
    
  - url: /robots\.txt
    static_files: static/robots.txt
    upload: static/robots\.txt
    secure: always
    
  # Main application handler
  - url: /.*
    script: auto
    secure: always

# Security headers
default_expiration: "1d"

# VPC connector (if using private resources)
# vpc_access_connector:
#   name: "projects/your-project/locations/us-central1/connectors/aerodrome-connector"

# Beta settings for performance
beta_settings:
  # Enable Cloud SQL connections
  cloud_sql_instances: 
    - "your-project:us-central1:aerodrome-db"
  
  # Use newer runtime features
  max_instances_per_class: 10
  
  # Enable request tracing
  enable_health_check: true

# Skip files during deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?tests/.*$
  - ^(.*/)?test_.*\.py$
  - ^(.*/)?.*_test\.py$
  - ^(.*/)?docs/.*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?LICENSE$
  - ^(.*/)?README.*$
  - ^(.*/)?Dockerfile.*$
  - ^(.*/)?docker-compose.*$
  - ^(.*/)?\.dockerignore$
  - ^(.*/)?\.gitignore$
  - ^(.*/)?\.gcloudignore$
  - ^(.*/)?cloudbuild\.yaml$
  - node_modules/
  - __pycache__/
  - \.pytest_cache/
  - \.coverage
  - \.venv/
  - venv/